config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  root to: 'pages#home'
  resources :pages

  get 'home_guest', to: 'pages#home_guest'

  get 'profile_guest', to: 'pages#profile_guest'
  patch 'profile_guest', to: 'pages#profile_update'

  get 'activities/:id/rerender', to: 'activities#rerender', as: :rerender


  # Devise
  devise_for :employees, :controllers => { :registrations => "employees/registrations" }
  devise_for :guests, :controllers => { :registrations => "guests/registrations" }

  # Employees
  namespace :admin do
    resources :bookings, only: [:index, :show, :edit, :update, :destroy]
    get 'my_activities', to: 'activities#my_activities'
    get 'my_activities2', to: 'activities#my_activities2'
    get 'dashboard', to: 'activities#dashboard'

    resources :activities do
      resources :bookings, only: [:new, :create]
      resources :availabilities
    end
  end

  # Guests
  resources :activities, only: [:index, :show, :new] do
    resources :bookings, only: [:create]
    resources :availabilities, only: [:show]
  end
  resources :bookings, only: [:index, :show, :destroy]


  resources :chatrooms do
    resources :messages, only: [:create]
  end
  
  patch 'notifications/mark_as_read', to: 'notifications#mark_as_read'
  patch 'notifications/mark_as_cleared', to: 'notifications#mark_as_cleared'
  get '/my_activities', to: 'activities#my_activities'
  get '/filter', to: 'activities#filter'
  get '/count', to: 'activities#count'

end

app/views/shared/_activities_index_nav.html.erb
<div class="navbar-wagon <%= yield(:navbar_class) %>">
  <!-- Logo -->
  <% if @date %>
    <a href="/filter?date=<%= @date.strftime("%Y-%m-%d") %>" class="navbar-wagon-brand" id="filter-button">
      <div class="ll"><%= image_tag "funnel.png", class: "logo filter-image" %></div>
    </a>
  <% else %>
    <a href="/filter" class="navbar-wagon-brand" id="filter-button">
      <div class="ll"><i class="fa fa-search funnel-logo" aria-hidden="true"></i></div>
    </a>
  <% end %>

  <!-- Notifications -->
<% is_displayed = current_guest.received_notifications.where(read: false).count > 0 ? '' : 'hide-notif' %>
<div class="flex-center nav-notif">
  <i class="fa fa-bell" aria-hidden="true"></i>
  <div class="notif-badge <%= is_displayed %>">
    <p><%= current_guest.received_notifications.where(read: false).count %></p>
  </div>
  <div class="notif-container hide-notif">
    <%= link_to 'Mark all as read', notifications_mark_as_read_path, method: :patch, class: "read" %>
    <%= link_to 'Clear all', notifications_mark_as_cleared_path, method: :patch, class: "cleared" %>
    <% current_guest.received_notifications.where(cleared: false).each do |notification| %>
      <%= render 'shared/notification-guest', notification: notification %>
    <% end %>
  </div>
</div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
  <%=link_to "Booked Activities", my_activities_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% img = current_guest.photo? ? current_guest.photo.url(:bright_face)  : 'jsut0cgif0nnmpalnwpn' %>
        <%= cl_image_tag img, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", 'data-toggle' => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%=link_to "Profile", profile_guest_path %></li>
          <li><%=link_to "Log Out", destroy_guest_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </div>

<div class="hidden-lg hidden-md">
    <div class="navbar-wagon-item">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%=link_to "Home", home_guest_path %></li>
        <li><%=link_to "Profile", profile_guest_path %></li>
        <li><%=link_to "Booked Activities", my_activities_path %></li>
        <li><%=link_to "Log Out", destroy_guest_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</div>
</div>

app/views/shared/_activity-info.html.erb
<div class="activities-details">

  <% img = @activity.photo? ? @activity.photo : 'iyq4gxp0oltwleiwafrx6' %>
  <div class="activity-picture" id="info-photo" style="background-image: url('<%= cl_image_path img %>');" ></div>

  <div class="activity-info">
    <div class="info">
      <h1 class="sub-title">Brief introducition to <%= @activity.name %></h1>
      <p><%= @activity.description %></p>
      <hr class="line-break">
        <h2><strong>Location: </strong><%= @activity.location %></h2>
        <h2><strong>Price: </strong>£<%= @activity.price %></h2>
        <h2><strong>Capacity: </strong><%= @activity.capacity %></h2>
        <h2><strong>Duration: </strong><%= @activity.duration %>h</h2>
    </div>
  </div>
</div>

app/views/shared/_activity-schedule.html.erb
<div class="schedule">
  <div id="calendar"></div>
</div>



<% content_for(:after_js) do %>
  <script>
    $('#calendar').fullCalendar({
      themeSystem: "bootstrap3",
      allDaySlot: false,
      defaultView: "agendaWeek",
      minTime: "09:00:00",
      maxTime: "18:00:00",
      header: {
            left: '',
            center: 'prev title next',
            right: ''
        },
        events: '/admin/activities/<%= @activity.id %>.json',
    });
  </script>
<% end  %>

app/views/shared/_admin-booking-info.html.erb
<% availability_id = params[:id] %>
<% availability = Availability.find(availability_id) %>
<% img = availability.activity.photo? ? availability.activity.photo : "yq4gxp0oltwleiwafrx6" %>


<div class="activities-details-booking">
  <div class="activity-info-booking">
    <div class="info-booking">
      <h1 class="sub-title">Booking Info</h1>
      <hr class="line-break">
        <h2><strong>Location: </strong><%= @activity.location %></h2>
        <h2><strong>Price: </strong>£<%= @activity.price %></h2>
        <h2><strong>Capacity: </strong><%= @activity.capacity %></h2>
        <h2><strong>Duration: </strong><%= @activity.duration %>h</h2>
        <h2><strong>When: </strong><%= availability.start_time.strftime("%A, %d %b %Y %l:%M %p") %></h2>
    </div>
  </div>

  <div class="activity-info-booking">
    <div class="info-booking">
      <h1 class="sub-title">Guests</h1>
      <hr class="line-break">
      <div class="people">
        <% @bookings = Booking.where("availability_id = #{availability.id}") %>
        <% @bookings.each do |booking| %>
        <div class="person">
          <% img = booking.guest.photo? ? booking.guest.photo.url(:bright_face) : "jsut0cgif0nnmpalnwpn" %>
          <% if booking.no_ppl > 1 %>
            <%= cl_image_tag img, class: "booker" %>
            <p class="guests">+<%= booking.no_ppl - 1 %></p>
          <% else %>
            <%= cl_image_tag img, class: "booker" %>
          <% end %>
          <h2 style="padding-left: 10px;"><%= booking.guest.first_name %></h2>
        </div>
        <% end %>
      <div>
    </div>
  </div>
</div>

app/views/shared/_booking_time_navbar.erb
<div class="navbar-wagon-d">
  <div class="date-choose" id="date-choose">
    <%# @date = Date.today %>
    <% @date = Date.parse(params[:date]) %>
    <%= link_to activity_path(@activity, date: (@date - 1.day).strftime('%d-%m-%Y')), remote: true do %>
      <i class="fa fa-angle-left"></i>
    <% end %>


    <h2><%= @date.strftime("%b %d, %Y") %></h2>
    <%= link_to activity_path(@activity, date: (@date + 1.day).strftime('%d-%m-%Y')), remote: true do %>
      <i class="fa fa-angle-right"></i>
    <% end %>
  </div>
  <div class="scrolls">
    <div class="bookings-wrapper">
      <% @availabilities.each do |availability| %>
        <div class="bookings">
          <p class="p-bar">
            <%= availability.timeslot.strftime("%I:%M %p") %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if current_guest %>
  <% if notice %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
  <% end %>
<% end %>

app/views/shared/_guests-filter-navbar.html.erb
<div class="navbar-wagon <%= yield(:navbar_class) %>" style="margin-bottom: 23px !important;">
  <!-- Logo -->
<%= link_to "Back", activities_path(:date => params[:date]), class: "samback" %>


 <h5 class="filter-title text-center">Filter</h5>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
  <%=link_to "Booked Activities", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <div class="navbar-wagon-item navbar-guest-fitler">
      <div class="dropdown">
        <% img = current_guest.photo? ? current_guest.photo.url(:bright_face)  : 'jsut0cgif0nnmpalnwpn' %>
        <%= cl_image_tag img, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", 'data-toggle' => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%=link_to "Profile", profile_guest_path %></li>
          <li> <%=link_to "Log Out", destroy_guest_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="hidden-lg hidden-md">
    <div class="navbar-wagon-item navbar-guest-fitler">
      <%= link_to "Reset", "#", class: "samback" %>
    </div>
  </div>
</div>


<%= content_for(:after_js) do %>
  <script>
    let navNotif = document.querySelector('.nav-notif');
    let notifContainer = document.querySelector('.notif-container');
    navNotif.addEventListener('click', function() {
      notifContainer.classList.toggle('hide-notif');
    });
  </script>
<% end %>

app/views/shared/_message.html.erb
<div class="message <%= user_is_messages_author ? 'right-side-msg' : '' %>">
  <% img = message.messageable.photo? ? message.messageable.photo.url(:bright_face)  : 'jsut0cgif0nnmpalnwpn' %>
  <%= cl_image_tag img, class: "avatar-msg" %>
  <div class="message-content">
    <p class="msg-author"><%= message.messageable.first_name %>:</p>
    <p><%= message.body %></p>
  </div>
</div>

app/views/shared/_nav.html.erb
<% if params[:controller] == 'activities' && params[:action] == 'filter' %>
  <%= render "shared/guests-filter-navbar" %>
<% elsif current_guest %>
  <%= render "shared/guest-nav" %>
<%  elsif current_employee %>
  <%= render "shared/employee-nav" %>
<% end %>

app/views/shared/_navbar2.html.erb
<div class="navbar-wagon-dd">
  <div class="info-next">
    <i class="fa fa-user" aria-hidden="true" id="box-icon"> </i>
     <p class="box"> 1 </p>
  </div>
  <div>
    <i class="fa fa-plus-circle" aria-hidden="true"></i>
    <i class="fa fa-minus-circle" aria-hidden="true"></i>
  </div>
  <%= link_to "Next", activity_dates_path(@activity, date: Date.today.strftime('%d-%m-%Y')), class: "next-link" %>
</div>

app/views/shared/_notification-employee.html.erb
<% activity = notification.availability.activity %>
<% availability = notification.availability %>
<% img = notification.notifierable.photo? ? notification.notifierable.photo.url(:bright_face)  : 'jsut0cgif0nnmpalnwpn' %>
<%= link_to admin_activity_availability_path(activity, availability) do %>
  <div class="notification">
    <%= cl_image_tag img, class: "avatar-msg" %>
    <p><%= notification.availability.activity.name %></p>
    <i class="fa  fa-commenting-o"></i>
  </div>
<% end %>

app/views/shared/_notification.html.erb
<% activity = notification.availability.activity %>
<% availability = notification.availability %>
<%= link_to activity_availability_path(activity, availability) do %>
  <div class="notification">
    <p><b><%= notification.availability.activity.name %></b>: notif from <b><%= notification.notifierable.first_name %></b></p>
  </div>
<% end %>

app/views/shared/_side-nav.html.erb
<% if current_employee %>
  <div class="main-container">
    <div class="sidebar"><%= render "shared/sidebar2" %></div>
    <div class="page-content"><%= yield %></div>
  </div>
<% else %>
  <%= yield %>
<% end %>

app/views/shared/_sidebar2.html.erb
<% if params[:controller] == 'admin/activities' && params[:action] == 'index'  %>
  <% activities = 'nav-active' %>
<% end %>

<% if params[:controller] == 'admin/activities' && params[:action] == 'dashboard' %>
  <% dashboard = 'nav-active' %>
<% end %>

<% if params[:controller] == 'admin/activities' && params[:action] == "my_activities2" %>
  <% bookings = 'nav-active' %>
<% end %>


<ul>
  <%= link_to admin_dashboard_path do %>
      <li class="sidebar-wagon-item sidebar-wagon-link <%= dashboard %>">
        <div class="sidebar-wagon-item">
          <div class="line <%= dashboard %>"></div>
          <i class="fa fa-bar-chart-o"></i>
          <p>Dashboard</p>
        </div>
      </li>
    <% end %>
  <%= link_to admin_my_activities2_path do %>
    <li class="sidebar-wagon-item sidebar-wagon-link <%= bookings %> " >
    <div class="sidebar-wagon-item">
    <div class="line <%= bookings %>"></div>
      <i class="fa fa-calendar-check-o"></i>
      <p>Calendar</p>
          </div>
    </li>
  <% end %>
  <%= link_to admin_activities_path do %>
    <li class="sidebar-wagon-item sidebar-wagon-link <%= activities %>">
      <div class="sidebar-wagon-item">
      <div class="line <%= activities %>"></div>
      <i class="fa fa-tags"></i>
      <p>Activities</p>
    </div>
    </li>
  <% end %>
</ul>