config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  root to: 'pages#home'
  resources :pages

  get 'home_guest', to: 'pages#home_guest'

  get 'profile_guest', to: 'pages#profile_guest'
  patch 'profile_guest', to: 'pages#profile_update'

  get 'activities/:id/rerender', to: 'activities#rerender', as: :rerender


  # Devise
  devise_for :employees, :controllers => { :registrations => "employees/registrations" }
  devise_for :guests, :controllers => { :registrations => "guests/registrations" }

  # Employees
  namespace :admin do
    resources :bookings, only: [:index, :show, :edit, :update, :destroy]
    get 'my_activities', to: 'activities#my_activities'
    get 'my_activities2', to: 'activities#my_activities2'
    get 'dashboard', to: 'activities#dashboard'

    resources :activities do
      resources :bookings, only: [:new, :create]
      resources :availabilities
    end
  end

  # Guests
  resources :activities, only: [:index, :show, :new] do
    resources :bookings, only: [:create]
    resources :availabilities, only: [:show]
  end
  resources :bookings, only: [:index, :show, :destroy]


  resources :chatrooms do
    resources :messages, only: [:create]
  end
  
  patch 'notifications/mark_as_read', to: 'notifications#mark_as_read'
  patch 'notifications/mark_as_cleared', to: 'notifications#mark_as_cleared'
  get '/my_activities', to: 'activities#my_activities'
  get '/filter', to: 'activities#filter'
  get '/count', to: 'activities#count'

end

app/models/activity.rb
class Activity < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :availabilities, dependent: :destroy
  belongs_to :employee
  CATEGORIES = ["Yoga", "Surfing", "Paddleboarding", "Watersports", "Snorkelling"]
  validates :name, :description, :location, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def filter
    @date = Date.parse(params[:date])
    @activities = Activity.all
    @activitiesForFilter = @activities.select {|activity| activity.availabilities.any? {|availability| availability.start_time.to_date == @date}}
  end

  def count
    date = Date.parse(params[:date])
    activities = Activity.where(category: params[:category]&.map(&:capitalize)).where("price <= ?", params[:price]).where("capacity >= ?", params[:capacity])
    activities = activities.select {|activity| activity.availabilities.any? {|availability| availability.start_time.to_date == date}}
    render json: {count: activities.length}
  end

  def index
    # binding.pry
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @category = params[:category]
    @price = params[:price]
    @numpeople = params[:numpeople]
    if params[:price] && params[:numpeople]
      # this will only be run once a filter form has been submitted

      if params[:price] != 0
        @activities = Activity.where(category: @category&.map(&:capitalize)).where("price <= ?", @price).order(price: :asc).where("capacity >= ?", @numpeople).order(capacity: :asc)
        @activities = @activities.select {|activity| activity.availabilities.any? {|availability| availability.start_time.to_date == @date}}
        @filter_flag = @activities.any?
        @first_enter_flag = false;
      else
        @activities = Activity.where(category: @category&.map(&:capitalize)).where("price = ?", 0).where("capacity >= ?", @numpeople).order(capacity: :asc)
        @activities = @activities.select {|activity| activity.availabilities.any? {|availability| availability.start_time.to_date == @date}}
        @filter_flag = @activities.any?
        @first_enter_flag = false;
      end
    else
      @activities = Activity.all
      @activities = @activities.select {|activity| activity.availabilities.any? {|availability| availability.start_time.to_date == @date}}
      @first_enter_flag = true;
    end
    respond_to do |format|
      format.html { render layout: 'guest' }
      format.js { render 'index', :locals => {date: @date} }
    end
  end

  def show
    @booking = Booking.new
    @date = Date.parse(params[:date])
    @activity = Activity.find(params[:id])
    @availabilities = @activity.availabilities.where("start_time > ? AND start_time < ?", @date, @date + 1)
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def rerender
    @date = Date.parse(params[:date])
    @activity = Activity.find(params[:id])
    @availabilities = @activity.availabilities.where("start_time > ? AND start_time < ?", @date, @date + 1)
  end
end

app/controllers/admin/activities_controller.rb
class Admin::ActivitiesController < ApplicationController

  before_action :authenticate_employee!

    def index
    @category = params[:category]
    @price = params[:price]
    @activities = Activity.where("category iLIKE '%#{@category}%'")
    end

  def show
    @activity = Activity.find(params[:id])
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.employee = current_employee
    if @activity.save
      redirect_to new_admin_activity_availability_path(@activity)
    else
      render "new"
    end
  end


  def edit
  end

  def update
  end

  def destroy
  end

  def my_activities
  end

  def my_activities2
    @my_availabilities = Availability.where('employee_id = ?', current_employee.id)
  end

  def dashboard
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :location, :capacity, :price, :description, :duration, :photo, :photo_cache, :category)
  end

  def get_photo_file_name
    params.require(:activity).permit(:@original_filename)
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/admin/activities/dashboard.html.erb
<div class="show-page-header" >
  <div class="calendar-header">
    <div class="top-line-show">
      <h1 style="text-align: left;">How are we doing this week?<br><small style="color: black;">Let's catch up with our KPIs</small></h1>
    </div>
  </div>
</div>


<div class="dashboard-page">

  <div class="top-stats">
    <div class="stat">
      <div class="stat-inside">
        <span>Most Popular Activity</span>
        <h2> Surfing</h2>
      </div>
    </div>
    <div class="stat">
      <div class="stat-inside">
        <span> Weekly Sales</span>
        <h2> $12,000</h2>
      </div>
    </div>
    <div class="stat">
      <div class="stat-inside">
        <span>Availabilities booked</span>
        <h2>43%</h2>
      </div>
    </div>
  </div>


  <div class="dashboard-chart-div">
    <span>Weekly Sales</span>
    <div class="dashboard-chart" id="chart_container"></div>
    <div></div>
  </div>

</div>



<%= content_for(:after_js) do %>
  <script>

    Highcharts.chart('chart_container', {
        title: {
            text: ''
        },

        subtitle: {
            text: ''
        },

        yAxis: {
            title: {
                text: 'Number of Guests'
            }
        },

        xAxis: {
        type: 'datetime'
        },

        legend: {
            layout: 'horizontal',
            align: 'left',
            verticalAlign: 'bottom'
        },

        plotOptions: {
            series: {
                label: {
                    connectorAllowed: false
                },
                pointStart: Date.UTC(2017, 0, 1),
                pointInterval: 200 * 3600 * 1000
            }
        },

        series: [{
            name: 'Surfing',
            data: [23, 37, 18, 30, 48, 12, 67]
        }, {
            name: 'Yoga',
            data: [32, 39, 56, 76, 80, 71, 89]
        }, {
            name: 'Paddleboarding',
            data: [23, 37, 18, 30, 48, 12, 67]
        }, {
            name: 'Snorkelling',
            data: [null, null, 56, 76, 80, 71, 89]
        }, {
            name: 'Watersports',
            data: [23, 37, 18, 30, 48, 12, 67]
        }],

        responsive: {
            rules: [{
                condition: {
                    maxWidth: 400
                },
                chartOptions: {
                    legend: {
                        layout: 'horizontal',
                        align: 'center',
                        verticalAlign: 'bottom'
                    },
                }
            }]
        }

    });

// pie chart thing
        $(function(){
      var $ppc = $('.progress-pie-chart'),
        percent = parseInt($ppc.data('percent')),
        deg = 360*percent/100;
      if (percent > 50) {
        $ppc.addClass('gt-50');
      }
      $('.ppc-progress-fill').css('transform','rotate('+ deg +'deg)');
      $('.ppc-percents span').html(percent+'%');
    });
  </script>
<% end %>

app/views/admin/activities/index.html.erb
<div class="show-page-header" >
  <div class="calendar-header">
    <div class="top-line-show">
      <h1>Your Activities</h1>
        <%= link_to new_admin_activity_path, class: "btn btn-primary", id: "add" do %>
          <i class="fa fa-plus"></i> Add new activity
        <% end %>
    </div>
  </div>

    <div class="tabs">
    <p class="tab active" id="schedule"> <%=  link_to "All", admin_activities_path %></p>
    <% @categories = Activity::CATEGORIES %>
    <% @categories.each do |category| %>
      <p class="tab active" id="schedule"><%=  link_to "#{category}", admin_activities_path(category: "#{category}") %></p>
      <% end %>
    </div>
</div>


<div class="container-fluid" style="padding: 30px;" id="list">
  <div class="row">
    <% @activities.each do |activity| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <% img = activity.photo? ? activity.photo : "yq4gxp0oltwleiwafrx6" %>
        <div class="card-index">
          <div class="left-side">
            <div class="picture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path img %>'); background-size: cover; background-position: center center;"></div>
          </div>
          <div class="right-side">
              <span><%= activity.name %></span>
          </div>
          <%= link_to "", admin_activity_path(activity), class: "card-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/activities/my_activities.html.erb
<% @my_availabilities = Availability.where('employee_id = ?', current_employee.id) %>

<div class="container">
  <div class="title">
    <h2>Your Activities</h2>
  </div>
  <% @my_availabilities.each do |availability| %>
    <div class="activity">
      <div class="colored-side"></div>
      <div class="act-date">
       <p>
        <strong><%= availability.start_time.strftime("%b %d, %Y") %></strong>
       </p>
       <p>
        <%= availability.start_time.strftime("%I:%M %p") %>
       </p>
      </div>
      <div class="act-right">
        <div class="act-cont">
          <div class="act-info">
            <p>
            <strong><%= availability.activity.name %></strong>
            <%= link_to activity_path(availability.activity),
            method: :delete,
            class: "delete-link",
            data: { confirm: "Are you sure?" } do %>
            <i class="fa fa-trash" aria-hidden="true"></i>
            <% end %>
            </p>
            <p>
            <%= availability.activity.location %>
            </p>
          </div>
          <div class="act-price">
            <p>
              <% @ppl = Booking.where("availability_id = #{availability.id}") %>
              <% @sumofppl = 0 %>
              <% @ppl.each do |i| %>
                <% @sumofppl += i.no_ppl %>
              <% end %>
              <%= @sumofppl %>/<%= availability.activity.capacity %>
            </p>
             <i class="fa fa-users" aria-hidden="true"></i>
          </div>
        </div>
        <div class="people">
          <% @bookings = Booking.where("availability_id = #{availability.id}") %>
          <% @bookings.each do |booking| %>
          <div class="person">
            <% img = booking.guest.photo? ? booking.guest.photo.url(:bright_face) : "jsut0cgif0nnmpalnwpn" %>
            <% if booking.no_ppl > 1 %>
              <%= cl_image_tag img, class: "booker" %>
              <p class="guests">+<%= booking.no_ppl - 1 %></p>
            <% else %>
                <%= cl_image_tag img, class: "booker" %>
             <% end %>
          </div>

          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/activities/my_activities2.html.erb
<div class="show-page-header" >
  <div class="calendar-header">
    <div class="top-line-show">
      <h1 style="text-align: left;">Week overview<br><small style="color: black;">Get a quick glance at all your activities bookings</small></h1>
    </div>
  </div>
</div>

<div class="calendar-container">
  <div id="calendar" style="background-color:white; padding: 40px 50px 0;"></div>
  <div class="status-bar" style="margin-top: 20px;">
    <ul>
      <li><p><i class="fa fa-circle" id="no-bookings"></i> No bookings</p> </li>
      <li><p><i class="fa fa-circle" id="bookings"></i> Bookings</p> </li>
      <li><p><i class="fa fa-circle" id="fully-booked"></i> Fully Booked</p> </li>
    </ul>
  </div>
</div>






<% content_for(:after_js) do %>
  <script>
    $('#calendar').fullCalendar({
      themeSystem: "bootstrap3",
      allDaySlot: false,
      firstDay: 1,
      defaultView: "agendaWeek",
      minTime: "09:00:00",
      maxTime: "18:00:00",
      header: {
            left: '',
            center: 'prev title next',
            right: 'agendaWeek,agendaDay'
        },
        events: '/admin/my_activities2.json',
    });
  </script>
<% end %>

app/views/admin/activities/new.html.erb
<div class="show-page-header" >
  <div class="calendar-header">
    <div class="top-line-show">
      <h1>Add an activity</h1>
        <%= link_to admin_activities_path, class: "btn btn-primary", id: "add" do %>
          <i class="fa fa-close"></i> Cancel
        <% end %>
    </div>
  </div>
  <div class="tabs" style="height: 65px;">
  </div>
</div>

<div class="container-add" >
  <div class="form-post" id="new-activity" style="margin: 0 50px 0; box-shadow: none;">
    <div class="new-activity">
      <%= simple_form_for [:admin, @activity], defaults: { input_html: { class: "activity-form"} } do |f| %>
        <% if @activity.errors.any? %>
          <div class="errors-container">
            <ul>
              <% @activity.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="row">
          <div class="col-xs-6">
            <div class="form-group string required activity_name">
              <label class="control-label string required texts" for="activity_name">
                <abbr title="required"></abbr> Name *
              </label>
              <input class="form-control string required activity-form" type="text" name="activity[name]" id="activity_name">
            </div>
          </div>
          <div class="col-xs-6">
            <div class="form-group string required activity_location">
              <label class="control-label string required" for="activity_location">
                <abbr title="required"></abbr> Location *</label>
                <input class="form-control string required activity-form" type="text" name="activity[location]" id="activity_location">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            <div class="form-group integer optional activity_capacity">
              <label class="control-label integer optional" for="activity_capacity">
              Capacity</label>
              <input class="form-control numeric integer optional activity-form" type="number" step="1" name="activity[capacity]" id="activity_capacity">
            </div>
          </div>
          <div class="col-xs-6">
            <div class="form-group integer optional activity_price">
              <label class="control-label integer optional" for="activity_price">Price</label>
              <input class="form-control numeric integer optional activity-form" type="number" step="1" name="activity[price]" id="activity_price">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            <div class="form-group select optional activity_category">
              <label class="control-label select optional" for="activity_category">
              Category
              </label>
              <select class="form-control select optional activity-form" name="activity[category]" id="activity_category">
                <option value="">Pick a category</option>
              <% Activity::CATEGORIES.each do |category| %>
                <option value="<%= category %>"><%= category %></option>
              <% end %>
              </select>
            </div>
          </div>
          <div class="col-xs-6">
            <div class="form-group select optional activity_category">
              <%= f.input :duration %>
          </div>
        </div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            <div class="form-group string required activity_description">
              <label class="control-label string required" for="activity_description">
              Description *
              </label>
              <input class="form-control string required activity-form" type="text" name="activity[description]" id="activity_description">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            <div class="form-group file optional activity_photo">
              <label  for="activity_photo" id="new-activity-text">Image of activity</label>
              <input class="inputfile" type="file" name="activity[photo]" id="file" data-multiple-caption="{count} files selected" multiple>
              <label class="new_button" for="file" ><i class="fa fa-upload"></i> <span> upload picture</span></label>
            </div>
            <div class="hidden">
              <%= f.input :photo %>
            </div>
          </div>
          <div class="col-xs-6" style="text-align: right; top: 34px;">
            <%= f.submit "Next", class: "btn btn-primary", id: "next-activity-button", style: "max-width: 220px;" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= content_for(:after_js) do %>
<script>
  var inputs = document.querySelectorAll( '.inputfile' );
  Array.prototype.forEach.call( inputs, function( input )
  {
    var label  = input.nextElementSibling,
      labelVal = label.innerHTML;
    input.addEventListener( 'change', function( e )
    {
      var fileName = '';
      if( this.files && this.files.length > 1 )
        fileName = ( this.getAttribute( 'data-multiple-caption' ) || '' ).replace( '{count}', this.files.length );
      else
        fileName = e.target.value.split( '\\' ).pop();
      if( fileName )
        label.querySelector( 'span' ).innerHTML = fileName;
      else
        label.innerHTML = labelVal;
    });
  });
</script>
<% end %>

app/views/admin/activities/show.html.erb
<div class="show-page-header" >
  <div class="calendar-header">
    <div class="top-line-show">
      <h1><%= @activity.name %></h1>
        <%= link_to new_admin_activity_availability_path(@activity), class: "btn btn-primary", id: "add"  do%>
        <i class="fa fa-plus"></i> add a new availability
        <% end %>
    </div>
  </div>

    <div class="tabs">
      <p class="tab " id="details"> Activity Details</p>
      <p class="tab active" id="schedule"> Activity Schedule</p>
    </div>
</div>
<div>

  <div class="activity-infos hidden"><%= render "shared/activity-info"  %></div>
  <div class="activity-schedule active"><%= render "shared/activity-schedule" %></div>
</div>


<% content_for(:after_js) do %>
<script>
    // hiding and showing activity-info and activity-schedule
    const details_tab = document.getElementById("details")
    const schedule_tab = document.getElementById("schedule")

    const details = document.querySelector(".activity-infos")
    const schedule = document.querySelector(".activity-schedule")

    schedule_tab.addEventListener("click", event => {
      details.classList = "hidden";
      schedule.classList = "active";
    });

    details_tab.addEventListener("click", event => {
      schedule.classList = "hidden";
      details.classList = "active";
    });

    window.addEventListener("load", () => {
      details_tab.click()
    });

</script>
<% end %>

app/views/admin/activities/showa.html.erb
  <div class="container-add" >
  <div class="top-line">
    <h1>Your Activity</h1>
      <%= link_to "add a new availability", new_admin_activity_availability(activity, class: "btn btn-primary", id: "add" %>
  </div>

  <div class="tabs">
  <a class="tab active" href="#">
    <p>Activity Details</p>
  </a>
  <a class="tab" href="#">
    <p>Activity Schedule</p>
  </a>
</div>

<div class="container-activity">
  <% img = @activity.photo? ? @activity.photo : 'iyq4gxp0oltwleiwafrx6' %>
  <div class="booking-show" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= cl_image_path img %>');">
    <div class="booking-content">
      <h1 id="title"><%= @activity.name %></h1>
      <h2><strong>Location: </strong><%= @activity.location %></h2>
      <h2><strong>Price: </strong>£<%= @activity.price %></h2>
      <h2><strong>Cpacity: </strong><%= @activity.capacity %></h2>
      <h2><strong>Duration: </strong><%= @activity.duration %>h</h2>
    </div>
  </div>
</div>

<%= link_to "Home", admin_activities_path, class: "btn btn-primary" %>
<div class="activity-info">
  <div class="info">
    <h1>Info</h1>
    <h3 class="sub-title">Brief introducition to <%= @activity.name %></h3>
    <p><%= @activity.description %></p>
    <hr class="line-break">
    <h3 class="sub-title">Location</h3>
    <p><%= @activity.location %></p>
  </div>

  <div class="schedule">
    <h1>Schedule</h1>
    <div id="calendar"></div>
  </div>
</div>
</div>
<% content_for(:after_js) do %>
  <script>
    $('#calendar').fullCalendar({
      themeSystem: "bootstrap3",
      allDaySlot: false,
      defaultView: "agendaWeek",
      minTime: "09:00:00",
      maxTime: "18:00:00",
      header: {
            left: '',
            center: 'prev title next',
            right: 'today'
        },
        events: '/admin/activities/<%= @activity_id %>/availabilities.json',
    });
  </script>
<% end  %>