config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  root to: 'pages#home'
  resources :pages

  get 'home_guest', to: 'pages#home_guest'

  get 'profile_guest', to: 'pages#profile_guest'
  patch 'profile_guest', to: 'pages#profile_update'

  get 'activities/:id/rerender', to: 'activities#rerender', as: :rerender


  # Devise
  devise_for :employees, :controllers => { :registrations => "employees/registrations" }
  devise_for :guests, :controllers => { :registrations => "guests/registrations" }

  # Employees
  namespace :admin do
    resources :bookings, only: [:index, :show, :edit, :update, :destroy]
    get 'my_activities', to: 'activities#my_activities'
    get 'my_activities2', to: 'activities#my_activities2'
    get 'dashboard', to: 'activities#dashboard'

    resources :activities do
      resources :bookings, only: [:new, :create]
      resources :availabilities
    end
  end

  # Guests
  resources :activities, only: [:index, :show, :new] do
    resources :bookings, only: [:create]
    resources :availabilities, only: [:show]
  end
  resources :bookings, only: [:index, :show, :destroy]


  resources :chatrooms do
    resources :messages, only: [:create]
  end
  
  patch 'notifications/mark_as_read', to: 'notifications#mark_as_read'
  patch 'notifications/mark_as_cleared', to: 'notifications#mark_as_cleared'
  get '/my_activities', to: 'activities#my_activities'
  get '/filter', to: 'activities#filter'
  get '/count', to: 'activities#count'

end

app/models/activity.rb
class Activity < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :availabilities, dependent: :destroy
  belongs_to :employee
  CATEGORIES = ["Yoga", "Surfing", "Paddleboarding", "Watersports", "Snorkelling"]
  validates :name, :description, :location, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def filter
    @date = Date.parse(params[:date])
    @activities = Activity.all
    @activitiesForFilter = @activities.select {|activity| activity.availabilities.any? {|availability| availability.start_time.to_date == @date}}
  end

  def count
    date = Date.parse(params[:date])
    activities = Activity.where(category: params[:category]&.map(&:capitalize)).where("price <= ?", params[:price]).where("capacity >= ?", params[:capacity])
    activities = activities.select {|activity| activity.availabilities.any? {|availability| availability.start_time.to_date == date}}
    render json: {count: activities.length}
  end

  def index
    # binding.pry
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @category = params[:category]
    @price = params[:price]
    @numpeople = params[:numpeople]
    if params[:price] && params[:numpeople]
      # this will only be run once a filter form has been submitted

      if params[:price] != 0
        @activities = Activity.where(category: @category&.map(&:capitalize)).where("price <= ?", @price).order(price: :asc).where("capacity >= ?", @numpeople).order(capacity: :asc)
        @activities = @activities.select {|activity| activity.availabilities.any? {|availability| availability.start_time.to_date == @date}}
        @filter_flag = @activities.any?
        @first_enter_flag = false;
      else
        @activities = Activity.where(category: @category&.map(&:capitalize)).where("price = ?", 0).where("capacity >= ?", @numpeople).order(capacity: :asc)
        @activities = @activities.select {|activity| activity.availabilities.any? {|availability| availability.start_time.to_date == @date}}
        @filter_flag = @activities.any?
        @first_enter_flag = false;
      end
    else
      @activities = Activity.all
      @activities = @activities.select {|activity| activity.availabilities.any? {|availability| availability.start_time.to_date == @date}}
      @first_enter_flag = true;
    end
    respond_to do |format|
      format.html { render layout: 'guest' }
      format.js { render 'index', :locals => {date: @date} }
    end
  end

  def show
    @booking = Booking.new
    @date = Date.parse(params[:date])
    @activity = Activity.find(params[:id])
    @availabilities = @activity.availabilities.where("start_time > ? AND start_time < ?", @date, @date + 1)
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def rerender
    @date = Date.parse(params[:date])
    @activity = Activity.find(params[:id])
    @availabilities = @activity.availabilities.where("start_time > ? AND start_time < ?", @date, @date + 1)
  end
end

app/controllers/admin/activities_controller.rb
class Admin::ActivitiesController < ApplicationController

  before_action :authenticate_employee!

    def index
    @category = params[:category]
    @price = params[:price]
    @activities = Activity.where("category iLIKE '%#{@category}%'")
    end

  def show
    @activity = Activity.find(params[:id])
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.employee = current_employee
    if @activity.save
      redirect_to new_admin_activity_availability_path(@activity)
    else
      render "new"
    end
  end


  def edit
  end

  def update
  end

  def destroy
  end

  def my_activities
  end

  def my_activities2
    @my_availabilities = Availability.where('employee_id = ?', current_employee.id)
  end

  def dashboard
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :location, :capacity, :price, :description, :duration, :photo, :photo_cache, :category)
  end

  def get_photo_file_name
    params.require(:activity).permit(:@original_filename)
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activities_list.html.erb
<div class="row">
  <div class="date-choose">
    <%= link_to activities_path(date: (date - 1.day).strftime('%d-%m-%Y')), remote: true do %>
    <h2><i class="fa fa-angle-left" id="arrow-left"></i></h2>
    <% end %>

    <h2><%= date.strftime("%b %d, %Y") %></h2>

    <%= link_to activities_path(date: (date + 1.day).strftime('%d-%m-%Y')), remote: true do %>
      <h2><i class="fa fa-angle-right" id="arrow-right"></i></h2>
    <% end %>
  </div>

  <%= link_to "Filter", filter_path(date: date), class: "btn btn-primary sam-custom-filter-button" %>

  <% if @activities.count == 0 && @first_enter_flag == true %>
    <h3>There are no activities available today</h3>
  <% end %>
  <% if @filter_flag == false %>
    <h3>There are no available activities today that match your filter criteria</h3>
  <% end %>
  <% @activities.each do |activity| %>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <% img = activity.photo? ? activity.photo : "yq4gxp0oltwleiwafrx6" %>
      <!-- the show page isn't working yet so I just linked it to the filter page, when its working change it back to show page -->
      <%= link_to activity_path(activity, date: date.strftime('%d-%m-%Y')), :action => 'go' do %>
        <div class="card samcustomcard" id="custom-card">
          <div class="top">
            <div class="picture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path img %>');"></div>
            <div class="card-category">
              <% if activity.price == 0 %>
                Free
              <% else %>
                £<%= activity.price %>
              <% end %>
            </div>
            <div id="card-duration">
              <% if activity.duration > 1 %>
                <%= activity.duration %> hours
              <% else %>
                <%= activity.duration %> hour
              <% end %>
            </div>
            <div id="card-capacity">
              <%= activity.capacity %>
              <i class="fa fa-user-o"></i>
            </div>
          </div>
          <div class="bottom" id="bottom-info-container">
            <div class="card-description samcustomdescription">
              <h2><%= activity.name %></h2>
            </div>

            <div class="scrolls">
              <div class="bookings-wrapper samcustombookingwrapper">
                <% activity.availabilities.each do |availability| %>
                  <!-- <h1><%= availability.start_time.to_date %></h1> -->
                  <% if availability.start_time.to_date == @date %>
                    <div class="bookings samcustombookings">
                      <p class="p-bar">
                        <%= availability.start_time.strftime("%I:%M %p") %>
                      </p>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
            <!-- <table>
              <tbody>
                <tr>
                  <td>

                  </td>
                </tr>
              </tbody>
            </table> -->
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/activities/create.html.erb
<h1>Activities#create</h1>
<p>Find me in app/views/activities/create.html.erb</p>

app/views/activities/destroy.html.erb
<h1>Activities#destroy</h1>
<p>Find me in app/views/activities/destroy.html.erb</p>

app/views/activities/edit.html.erb
<h1>Activities#edit</h1>
<p>Find me in app/views/activities/edit.html.erb</p>

app/views/activities/filter.html.erb
<div class="price-range">
  <%= form_tag(activities_path, method: :get, name: "priceform") do %>
  <% arr = [] %>
  <h6 style="margin-bottom: 0px !important; margin-left: 4px !important; margin-top: 20px !important;">Sports Categories</h6>
  <hr style="margin-top: 10px !important; margin-bottom: 10px !important; margin-left: 4px !important; margin-right: 4px !important;">
    <% @activities.each_with_index do |activity, index| %>
      <% unless arr.include?(activity.category) %>
        <% arr << activity.category %>
        <div class="pretty p-default p-round p-thick shiftright">
          <input type="checkbox" name="category[]", id="category[]", value="<%= activity.category %>", checked="checked", class="respondToInput"/>
          <div class="state p-primary-o">
            <label class="category"><%= activity.category.capitalize %></label>
          </div>
        </div>
        <br>
        <br>
      <% end %>
    <% end %>

    <h6 style="margin-bottom: 0px !important; margin-left: 4px !important; margin-top: 20px !important;">List only free activities</h6>
    <hr style="margin-top: 7px !important; margin-bottom: 7px !important; margin-left: 4px !important; margin-right: 4px !important;">
    <div class="pretty p-default p-round p-thick shiftright">
      <input type="checkbox" name="free", id="free", value="0", class="category"/>
      <div class="state p-primary-o">
        <label class="category"> Free Activities</label>
      </div>
    </div>
    <hr style="margin-top: 7px !important; margin-bottom: 7px !important; margin-left: 4px !important; margin-right: 4px !important;">
    <br>
    <br>

<div class="encapsulate">
    <div class="slider">
      <span id="ex6CurrentSliderValLabel" class="filter-subtitle">Filter by maximum price: £<span id="priceSliderVal">50</span></span>

      <input id="price"  name="price" type="text" data-slider-min="0" data-slider-max="100" data-slider-step="1" data-slider-value="50" data-slider-tooltip="hide" data-slider-enabled="true"/>
      <br>
      <br>
      <span id="ex7CurrentSliderValLabel" class="filter-subtitle">Filter by minimum number of people: <span id="peopleSliderVal">1</span></span>

      <input id="capacity" name="numpeople" type="text" data-slider-min="0" data-slider-max="20" data-slider-step="1" data-slider-value="1" data-slider-tooltip="hide"/>
    </div>
</div>


    <input type="hidden" name="date" value="<%= params[:date] %>">
    <%= submit_tag '', class: "filter btn btn-primary", id: "submit" %>
  <% end %>
</div>

<%= content_for(:after_js) do %>
  <script>
   let priceSliderValBeforeClick = 0;
    document.getElementById('free').addEventListener('change', () => {
      const priceSlider = document.getElementById('price');
      const priceSliderVal = document.getElementById('priceSliderVal')
      var checkBx = document.getElementById('free')
      if (checkBx.checked) {
        $("#price").slider("disable");
        if (buildCategoryArray() === "") {
          var arr = <%= raw @activitiesForFilter.to_json %>;
          var str = "";
          for (var i = 0 ; i < (arr.length); i++)
          {
            str += "category[]=" + arr[i].category + "&";
          }
          //category will be empty so it will try find activities with price equal to zero but it cant do that because categories are empty
          fetch(`/count?price=${0}&capacity=${$('#capacity').val()}&${str}date=${'<%= params[:date] %>'}`)
          .then(response => response.json())
          .then(data => {
            document.getElementById('submit').value = `show ${data.count} results`
          })
          priceSliderValBeforeClick = priceSlider.value;
          priceSlider.value = 0;
        }

        if (buildCategoryArray() != ""){
          var arr = <%= raw @activitiesForFilter.to_json %>;
          var str = "";
          for (var i = 0 ; i < (arr.length); i++)
          {
            str += "category[]=" + arr[i].category + "&";
          }
          //category will be empty so it will try find activities with price equal to zero but it cant do that because categories are empty
          fetch(`/count?price=${0}&capacity=${$('#capacity').val()}&${buildCategoryArray()}&date=${'<%= params[:date] %>'}`)
          .then(response => response.json())
          .then(data => {
            document.getElementById('submit').value = `show ${data.count} results`
          })
          priceSliderValBeforeClick = priceSlider.value;
          priceSlider.value = 0;
        }
      }
      else {
        if (buildCategoryArray() === "") {
        $("#price").slider("enable");
          document.getElementById('submit').value = `show 0 results`
          priceSlider.value = priceSliderValBeforeClick;
        }

        if (buildCategoryArray() != "") {
          console.log("we're here");
          console.log(priceSliderValBeforeClick);
          priceSlider.value = priceSliderValBeforeClick;
          console.log(priceSlider.value);
        $("#price").slider("enable");
        fetch(`/count?price=${$('#price').val()}&capacity=${$('#capacity').val()}&${buildCategoryArray()}&date=${'<%= params[:date] %>'}`)
          .then(response => response.json())
          .then(data => {
            document.getElementById('submit').value = `show ${data.count} results`
          })
          }
      }
      })

    $("#price").slider();
    $("#price").on("change", function(e) {
      $("#priceSliderVal").text(e.value.newValue);
      fetch(`/count?price=${e.value.newValue}&capacity=${$('#capacity').val()}&${buildCategoryArray()}&date=${'<%= params[:date] %>'}`)
        .then(response => response.json())
        .then(data => {
          document.getElementById('submit').value = `show ${data.count} results`
        })
    });

    $("#capacity").slider();
    $("#capacity").on("change", function(e) {
      $("#peopleSliderVal").text(e.value.newValue);
      if (buildCategoryArray() === "") {

      var arr = <%= raw @activitiesForFilter.to_json %>;
      var str = "";
      for (var i = 0 ; i < (arr.length); i++)
      {
        str += "category[]=" + arr[i].category + "&";
      }

      fetch(`/count?price=${0}&capacity=${e.value.newValue}&${str}&date=${'<%= params[:date] %>'}`)
        .then(response => response.json())
        .then(data => {
          document.getElementById('submit').value = `show ${data.count} results`
        })
      }
      else{
        fetch(`/count?price=${$('#price').val()}&capacity=${e.value.newValue}&${buildCategoryArray()}&date=${'<%= params[:date] %>'}`)
        .then(response => response.json())
        .then(data => {
          document.getElementById('submit').value = `show ${data.count} results`
        })
      }
    });

    document.querySelectorAll('.respondToInput').forEach(checkbox => {
      checkbox.addEventListener('change', (e) => {
        var checkBx = document.getElementById('free')
        var arr = <%= raw @activitiesForFilter.to_json %>;
        var str = "";
        for (var i = 0 ; i < (arr.length-1); i++)
        {
          str = "category[]=" + arr[i].category + "&";
        }
        if (buildCategoryArray() === "" && checkBx.checked)
        {
          fetch(`/count?price=${0}&capacity=${$('#capacity').val()}&${str}&date=${'<%= params[:date] %>'}`)
          .then(response => response.json())
          .then(data => {
            document.getElementById('submit').value = `show ${data.count} results`
          })
        }
        if (buildCategoryArray() === "" && checkBx.checked === false)
        {
          document.getElementById('submit').value = `show 0 results`
        }

        if (buildCategoryArray() != "" && checkBx.checked) {
          fetch(`/count?price=${0}&capacity=${$('#capacity').val()}&${buildCategoryArray()}&date=${'<%= params[:date] %>'}`)
          .then(response => response.json())
          .then(data => {
            document.getElementById('submit').value = `show ${data.count} results`
          })
        }

        if (buildCategoryArray() != "" && checkBx.checked === false) {
          fetch(`/count?price=${$('#price').val()}&capacity=${$('#capacity').val()}&${buildCategoryArray()}&date=${'<%= params[:date] %>'}`)
          .then(response => response.json())
          .then(data => {
            document.getElementById('submit').value = `show ${data.count} results`
          })
        }

      })
    })

    function buildCategoryArray() {
      arr = []
      document.querySelectorAll('.respondToInput').forEach(checkbox => {
        if (checkbox.checked === true) {
            arr.push(`category[]=${checkbox.value}`)
        }
      })
      return arr.join('&')
    }
</script>
<% end %>

app/views/activities/index.html.erb
<div class="container-fluid" id="list">
  <%= render 'activities_list', date: @date %>
</div>

app/views/activities/index.js.erb
var container = document.getElementById('list')
container.innerHTML = '<%= j render "activities_list", date: date %>'
// var link = document.getElementById('filter-button')
// console.log("link", link)
// link.href = "filter?date=<%= @date.strftime('%Y-%m-%d')%>"

app/views/activities/new.html.erb
<%= content_for(:navbar_class, "navbar-home") %>
<div style=" background-size: cover; background-color: #F9F9F9; background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 1%), url('https://images.unsplash.com/photo-1504619679259-7db48eb87a0b?auto=format&fit=crop&w=1680&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D');">
<div class="container" style=" width: 37%; background-color: transparent; border-radius: 20px; color: white; padding-top: 70px;" >

<h1>Add an activity</h1>
<div class="transparent-form">
<%= simple_form_for [@activity] do |f| %>
<% if @activity.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @activity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :capacity %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :duration %>
  <%= f.input :category, :collection => Activity::CATEGORIES %>
  <%= f.input :photo, label: "Image of activity" %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Add", class: "btn btn-primary"%>
<% end %>
</div>

</div>
</div>

app/views/activities/rerender.js.erb
console.log('hello!')
step2_hello = document.getElementById('step2_form')
step2_hello.innerHTML = "<%= j render 'shared/step2', hidden: false %>";


// hiding and showing step 1 and 2
submit_hello = document.querySelector('.submit-step')

// selecting a time
timeslots_hello = document.querySelectorAll(".bookings")
timeslots_hello.forEach(timeslot => {
  timeslot.addEventListener("click", event => {
    timeslots_hello.forEach(timeslot => timeslot.classList.remove('selected'));
    event.currentTarget.classList.add('selected');
    submit.click();
  });
});

app/views/activities/show.html.erb
<% img = @activity.photo? ? @activity.photo : 'iyq4gxp0oltwleiwafrx6' %>
<div class="booking-show" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= cl_image_path img %>'); width: 100%; height: 200px; background-size: cover; background-position: center;">
  <div class="booking-content">
  </div>
</div>

<div class="container samcontainer">
  <div class="row sam-row">
    <div class="samitem" id="name" style="width: 30%; margin-top: 10px;"><p class="sam-name"><%= @activity.name.capitalize%></p></div>
    <div class="location-info">
    <div class="samitem" id="location"><h4 class="sam-location"><%= @activity.location.capitalize%></h4></div>
    <div class="Location-icon" style="float:right; margin-top: 14px;"> <%= cl_image_tag 'placeholder_akrtrs', :width=>20, :height=>20, :crop=>:fit%></div>
    </div>
  </div>
  <hr style="margin-top: 8px !important; border-color: #d3d7dd !important; margin-left: 5px; margin-right: 5px; margin-bottom: 8px !important;">

  <div class="container sam-innercontainer">
    <h6 class="sam-subheadings">Brief introduction to <%= @activity.category %></h6>
    <p class="sam-description"><%= @activity.description %></p>
    <hr style="margin-top: 10px !important; border-color: #d3d7dd !important; margin-left: 1px; margin-right: 1px;">
    <h6 class="sam-subheadings">Location</h6>
    <div id="map" style="margin-bottom: 140px; height: 200px; width: 100%; background-image: url('<%= cl_image_path 'shandrani-map2_qltdro'%>'); background-size: cover;"><div class="location-icon-map" style="padding-top: 108px; padding-left: 87px;"><%= cl_image_tag 'placeholder_akrtrs', :width=>25, :height=>30, :crop=>:fit %></div></div>
  </div>
</div>
<%= render "shared/booking_form" %>

app/views/activities/update.html.erb
<h1>Activities#update</h1>
<p>Find me in app/views/activities/update.html.erb</p>